server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/os?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password:
mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

